name: clang-format check

on:
  pull_request:
    branches: [ develop ]

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Run clang-format on diff
        run: ./Support/Scripts/run_clang_format_diff.sh $GITHUB_BASE_REF $GITHUB_HEAD_REF
